### ISSUE TITLE
CityCoins rewarding homicide reduction nationally

### ISSUE THREAD

**Issue by pstan26** [citycoins/governance#28]
Abstract: Combine all CityCoins into one citycoin and launch every city all at once rewarding respective city’s police department for homicide reduction. A moral inversion of the [disastrous](https://www.politico.com/news/2022/02/24/oakland-mayor-defund-police-00011387) [“defund the police”](https://x.com/cremieuxrecueil/status/1758986463448814028?s=46) to simply “reward the police” for demonstrated homicide reduction.

The CityCoin initiative proposes a unified approach to leveraging cryptocurrency for municipal benefit, focusing on enhancing public safety through police department incentives. Here’s a concise overview of the proposal, including the mechanism for homicide reduction rewards:

### CityCoin Initiative Simplified:

- **Single CityCoin for All:** Introduces CityCoin as a universal cryptocurrency with its unique market value, replacing individual city tokens.
  
- **Yield Distribution Mechanics:**
  - **70% Yield to Holders:** CityCoin holders receive 70% of the Bitcoin yield generated.
  - **30% Yield for Police:** The remaining 30% is allocated to city police departments to fund public safety initiatives, specifically targeting homicide reduction.

- **Mining and Fund Allocation:**
  - **City-Specific Mining:** Individuals mine CityCoin by sending STX to addresses designated for their city, which are then used to generate yield.
  - **Early Adoption Benefits:** The first city to participate gets an additional collective 30% yield intended for other cities. Subsequent cities receive their 30% plus a portion of the yield from cities that join later.

- **Ensuring Public Safety:**
  - **Link to Homicide Reduction:** Police department funding is directly tied to achieving measurable reductions in the city’s homicide rate.
  - **Community Verification:** CityCoin holders play a role in validating reported homicide reductions, enabling the release of funds, ensuring transparency and community involvement.

### Key Features:

- **Streamlines Cryptocurrency Use:** Simplifies the cryptocurrency landscape for cities by offering a single, versatile CityCoin.
- **Motivates Early Adoption:** Encourages cities to participate early through a tiered incentive model that rewards the initial and subsequent cities differently.
- **Directly Supports Public Safety:** Aligns cryptocurrency yield with tangible benefits by funding police efforts to reduce homicides.
- **Community-Centric Verification:** Involves CityCoin holders in the process, adding an extra layer of validation to the funding mechanism.

### Conclusion:

The CityCoin initiative represents an innovative blend of cryptocurrency application and civic engagement. It promises not only to provide a financial mechanism for enhancing public safety but also to foster community involvement and accountability. By simplifying the cryptocurrency model for municipal use and directly linking financial incentives to public safety outcomes, CityCoin sets a new precedent for digital currencies' role in societal improvement.

**Comment by pstan26** [comment]
What would be interesting too is to tweet stats daily and reward in real time. Would create competition between cities and ongoing narrative. Would need an oracle.

**Comment by donieguy** [comment]
This is a noble proposal and intent. 

However, I think the enhancement of police forces is a polarizing topic for most. With CityCoins' current notoriety and public perception of cryptocurrencies as a whole, many will associate the two negatively.

This is because public perception has a certain view of Bitcoin, Stacks, and Web3. A perception that has been tainted with scams, companies going bankrupt, and the loss of investor funds.

If we want to build trust with the public, we need to begin at the top and let it flow down gradually with time. Above all though, we need to come together and make decisions.

**Comment by mavecillas** [comment]
I actually believe this will have a positive outlook. As you said crypto has been filled with scams, laundering and even terrorist organizations. What better way to clean up that image than teaming up with the police. There’s a big movement of retired citizens and law abiding citizens who will look positively to Citycoins if they find out we are helping out police officers.

**Comment by pstan26** [comment]
Thank you for your perspective. This proposal stands on the principle that action towards a noble cause, even if polarizing, is vital. It acknowledges the unintended consequences of the "defund the police" movement, particularly on marginalized communities. By aligning with a clear moral standpoint—enhancing public safety—we invite alignment and attention, crucial for impactful change. This isn't just about funding; it's about standing for community well-being, demonstrating moral authority by addressing real needs through innovative means.

**Comment by Tim-Butterfield** [comment]
It is an interesting idea.  If there is only a single coin, which police departments of which cities would benefit?  Would this be only for the very large cities or would very small citieis also benefit?  How would allocation of percentages be determined for the various cities, suburbs, and towns?  Is this USA only or international?  Also, would this replace the existing MIA and NYC and how might those cities feel about this change?

**Comment by pstan26** [comment]
> It is an interesting idea. If there is only a single coin, which police departments of which cities would benefit? Would this be only for the very large cities or would very small citieis also benefit? How would allocation of percentages be determined for the various cities, suburbs, and towns? Is this USA only or international? Also, would this replace the existing MIA and NYC and how might those cities feel about this change?

CityCoin could aim to support both large and small communities by introducing a unified cryptocurrency. The allocation for police departments will use a clear formula, factoring in city size, crime rates, and unique needs, to ensure fair distribution across all areas. Initially focusing on the U.S., there's no reason it can't go international, embracing cities worldwide. Transitioning from city-specific coins like MIA and NYC to CityCoin involves open dialogue, aiming to enhance public safety globally while considering each community's perspective.

**Comment by pstan26** [comment]
> Exactly my questions as well. This is an idea that sounds good on paper, but will most likely not scale very well.

For sake of efficiency, try steel-manning how it could scale.

**Comment by Tim-Butterfield** [comment]
> CityCoin could aim to support both large and small communities by introducing a unified cryptocurrency. The allocation for police departments could use a clear formula, factoring in city size, crime rates, and unique needs, to ensure fair distribution across all areas. Initially focusing on the U.S., there's no reason it can't go international, embracing cities worldwide. Transitioning from city-specific coins like MIA and NYC to CityCoin involves open dialogue, aiming to enhance public safety globally while considering each community's perspective.

One potential issue with scaling is that expanding the distribution to more and more cities will reduce what is given to earlier individual cities.  As each new city added wants a share, that share (of the overall percentage) will have to come from other cities.  For example, the first (and only) city may get 100% of possible share.  Adding a second similar sized city would give each 50% of the total.  The first city has already lost 50% of the total share.  Adding more cities and differing sized cities would further reduce the share each prior city receives.  In order to keep a similar dollar value to each prior city, the total available would have to keep expanding to cover the increased distributions.  Would that continued expansion be sustaniable?

**Comment by pstan26** [comment]
> We don't need to fix the police system of funding. We should simply create a mechanism to supplement all localities as whole.

For our proposal to succeed and align with Miami's priorities, it must focus on homelessness, housing, or policing. Diversifying beyond these areas risks losing focus and effectiveness, as the city will likely redirect funds to these critical issues if our proposal does not. A concentrated approach ensures our efforts are impactful and in harmony with the city's immediate needs, avoiding the potential for our proposal to be overlooked in favor of other pressing community challenges.

You’re welcome to submit a proposal that focuses on homeless, housing, or police. Needs to be one of those.

**Comment by pstan26** [comment]
> One potential issue with scaling is that expanding the distribution to more and more cities will reduce what is given to earlier individual cities. As each new city added wants a share, that share (of the overall percentage) will have to come from other cities. For example, the first (and only) city may get 100% of possible share. Adding a second similar sized city would give each 50% of the total. The first city has already lost 50% of the total share. Adding more cities and differing sized cities would further reduce the share each prior city receives. In order to keep a similar dollar value to each prior city, the total available would have to keep expanding to cover the increased distributions. Would that continued expansion be sustaniable?

Understood, with each city having its own treasury address and exclusive rights to its yield upon police department acceptance, the distribution remains fair and unaffected by new cities joining. This structure ensures that the introduction of additional cities doesn't dilute the share of existing participants. Instead, each city benefits directly from its contributions and efforts towards public safety, maintaining the integrity and sustainability of the initiative without impacting the yield allocated to earlier cities.

**Comment by CrypDohDS** [comment]
This is good. There is a moral obligation to create safety for people everywhere in the world. Municipal police funding is an established, fair, and honorable institution. I am in full support of bringing CityCoins to 1 token and all people.

**Comment by Tim-Butterfield** [comment]
This should be an award for achieved results instead of an assistance toward hopeful results.  It may be useful to allow each department to apply and show what results they have achieved for their sized city.

**Comment by pstan26** [comment]
> This should be an award for achieved results instead of an assistance toward hopeful results. It may be useful to allow each department to apply and show what results they have achieved for their sized city.

Yes, thanks edited the OP to make that more clear.

**Comment by donieguy** [comment]
For CityCoins to succeed it needs to rebrand and think bigger than singular cities.

It's a noble project, funding police departments for morality's sake. But it will most likely fail. Sorry, but I sincerely think there will not be enough support for this type of ideology. Not at this stage of global public adoption anyways.

Patrick, your attacks towards me and your knee jerk GitHub proposal to my own tells me that you're not ready for the leadership that comes with this type of project.

For 2 years, investors have reached out asking questions about CC, and you have been absent. Now, when all of a sudden your leadership is threatened, at a perfectly timed moment of the cryptocurrency bull market, you have come out of the shadows.

CC was launched with the statement that there would be no pre-mine or ability to fill greedy pockets. That all miners and participants would have an equal say, yet the emissions of the CC blockchain was abnormally high when it was first created, and then later updated to a much smaller emissions rate.

This in turn has created just a handful of wallets who own more than 40% of the total supply; most likely the people who were here first. Some would call this defrauding investors by artificially inflating assets.

**Comment by Tim-Butterfield** [comment]
It may also be possible to think of CityCoins as municipal focused crypto with different coins for different purposes.  it can be an entire ecosystem of this type of crypto.  Some coins like MIA, NYC, and others may be for local municipal projects.  Other coins may be for police results awards.  Still other coins may have additional purposes.  CityCoins does not need to be limited to only a single type of coin.

**Comment by pstan26** [comment]
> For CityCoins to succeed it needs to rebrand and think bigger than singular cities.
> 
> It's a noble project, funding police departments for morality's sake. But it will most likely fail. Sorry, but I sincerely think there will not be enough support for this type of ideology. Not at this stage of global public adoption anyways.
> 
> Patrick, your attacks towards me and your knee jerk GitHub proposal to my own tells me that you're not ready for the leadership that comes with this type of project.
> 
> For 2 years, investors have reached out asking questions about CC, and you have been absent. Now, when all of a sudden your leadership is threatened, at a perfectly timed moment of the cryptocurrency bull market, you have come out of the shadows.
> 
> CC was launched with the statement that there would be no pre-mine or ability to fill greedy pockets. That all miners and participants would have an equal say, yet the emissions of the CC blockchain was abnormally high when it was first created, and then later updated to a much smaller emissions rate.
> 
> This in turn has created just a handful of wallets who own more than 40% of the total supply; most likely the people who were here first. Some would call this defrauding investors by artificially inflating assets.

Addressing your concerns, no attacks are intended, and apologies if you interpreted anything in that way.

I’m a contributor, and posting a proposal which doesn’t have to be accepted or even entertained. I’d happily support whatever sounds good. Beyond this I’m only trying to ensure the treasury doesn’t get drained by a request from the city. I’ve made no profit contributing, and don’t intend to financially benefit from CityCoins. 

I look forward to your and others’ comments regarding proposals specifically. Be well.

**Comment by pstan26** [comment]
> It may also be possible to think of CityCoins as municipal focused crypto with different coins for different purposes. it can be an entire ecosystem of this type of crypto. Some coins like MIA, NYC, and others may be for local municipal projects. Other coins may be for police results awards. Still other coins may have additional purposes. CityCoins does not need to be limited to only a single type of coin.

Yes just be mindful of fracturing into different markets which can be costly and difficult to deal with.

**Comment by donieguy** [comment]
For sake of efficiency, try steel-manning how it could scale.

Ok then, I guess I will just ignore this comment.

Ultimately, the direction that CC goes is out of my control. I am only a voter that holds nowhere near enough to sway the votes of a few people that hold well over 40% of the total supply of CC.

This project's ultimate success or failure depends on those few voters. Which, in my opinion, is another core issue with this project.

**Comment by donieguy** [comment]
This is why we need to rebrand and show the US Federal Government how we can automate one of their systems **for profit**. 

Patrick, I don't know you. I don't trust you. We owe it to these people, these investors, to make the best fucking product ever. Something trustworthy, audited, and reliable.

We can't expect normal people to want to read source code. The US Government just approved the Bitcoin ETF. They are open to regulating the cryptocurrency market and this could be a pivotal moment in history to show them what trustworthy code can do on a publicly auditable blockchain.

**Comment by mavecillas** [comment]
> This is why we need to rebrand and show the US Federal Government how we can automate one of their systems **for profit**.
> 
> Patrick, I don't know you. I don't trust you. We owe it to these people, these investors, to make the best fucking product ever. Something trustworthy, audited, and reliable.
> 
> We can't expect normal people to want to read source code. The US Government just approved the Bitcoin ETF. They are open to regulating the cryptocurrency market and this could be a pivotal moment in history to show them what trustworthy code can do on a publicly auditable blockchain.
> 
> We need their regulatory framework.

Bro it’s a good idea I’m a schizo trust me I was born to lead

**Comment by Rapha-btc** [comment]
I like the idea of using a % of CityCoins yield to reward police for realized results, nodding to what Tim, Mavecillas, and Patrick suggested.

Keeping CityCoins unique to each city ensures targeted benefits (treasuries) and sense of citycoiner-ship, 

and using blockchain for greater audit transparency and real world data ownership makes a lot of sense to me.

**Comment by Rapha-btc** [comment]
Keeping city treasuries and entities separate allows for varied experiments, and if one succeeds, it can guide others. Unlike a single citycoin, failure doesn't impact all. What works for Miami might not suit New York City. This approach favors competition between cities.

**Comment by friedger** [comment]
If we want competing cities, why a single coin?

We don't need crypto to support police. We can support police directly. Or is this proposal about incentives for the police to work better? I haven't understood the tokenomics yet. 

I like the current idea of CC being a local currencies on commons infrastructure instead of on paper.

"We need to move from the monoculture of one currency (centralized, efficient) to a permaculture of many different currencies (decentralized, resilient)." from https://citizenwallet.xyz/

**Comment by Tim-Butterfield** [comment]
Just to be clear, I was not suggesting using a percentage of CC yields go to reward police.  I suggest creating a new, separate coin as a mechanism for rewarding police.

We have the opportunity for separate experiments.  We can vote for different changes for each coin.  They do not all need to follow the same path.  In fact, MIA and NYC have already diverged somewhat.  It would be useful to let each separate experiment play out, seeing what happens to coin values and seeing which has the most benefits for the locals of that city.  If we begin co-mingling funds, it would muddy the waters and prevent completion of any experiment.  This is why I propose a police award coin be entirely separate from the MIA and NYC coins.  But, before that coin is activated, we should clarify how it will operate with regards to award scheduling and result verification vs mining, stacking, etc.

**Comment by donieguy** [comment]
This path is not scalable. We need to focus on solving our own systemic issues before we can effect change. Separate treasuries will lead to an ever-increasing capital flow where profit is highest; NYC. This will eventually lead to a single CC and a single city with a larger and ever-growing treasury, effectively overshadowing other cities and their ability to compete.

**Comment by Tim-Butterfield** [comment]
Once we begin to fund local projects, the growth should flow towards the city experiencing greater benefits and thus greater PR from those projects.  That would be part of the competition between the cities, which can provide the greatest value both to the locals and to that CC for a given CC spend.  A local spend that helps locals, but harms that CC, would reduce growth of that CC.  It needs to be a benefit to both parties in order to foster growth.

**Comment by donieguy** [comment]
I adamantly believe this is an idea that sounds good on paper, but will not scale as you all envision it.

Ultimately, the direction of both CC blockchains will be determined by the very few; another systemic issue plaguing this project.

**Comment by Rapha-btc** [comment]
To Donie's point: Perhaps creating a mechanism to allow citycoin holders to exit could counterbalance the fact that ownership has yet to become more decentralized. I am not proposing this idea but rather asking community leaders for their opinions on it. I am aware that this idea has been proposed by others before.

How could an exit be facilitated? One could allow those who voted "no" to a proposal to burn their MIA or NYC in exchange for their fair share of the respective treasuries, calculated as CC tokens owned / total supply * total treasury.

Obviously, the price of MIA and NYC would instantly rise so that the market caps would match respective treasuries. However, treasuries would potentially take a blow initially from those discontent with the proposals. Nevertheless, this could be healthy in the long term, allowing for capital to flow more freely and be attracted rather than be captive. In my experience, facilitating the flow of capital is desirable.

**Comment by Tim-Butterfield** [comment]
One very easy way to exit has been discussed previously.  That is the burn for a tax deduction.  Personally, I would prefer this to a calculated percent of treasury.  The burn would increase the value of those who continue to hold.  This would work for both MIA and NYC.  By comparison, any giant spend such as what Miami has done previously would greatly reduce the calculated percentage of the treasury.  Also, I don't think we have that kind of access to the Miami treasury.  If I remember correctly,  think we can only spend the stacking rewards, but not the principle.  And, even small spends for NYC would have a slight effect over time.  This makes the burn easier as there isn't anyone to say no to it.

**Comment by Rapha-btc** [comment]
Thank you for sharing, Tim. Can you explain how this mechanism works?

Correct me if I'm wrong but this mechanism would not be inclusive for those not entitled to tax deductions, such as non-residents who are CC holders. Would you deny them to exit? For that reason, I would favor a permissionless right to exit over a tax-efficient one. 

If a burn for a percentage of the treasury exit isn't possible for MIA, but a burn for a tax deduction is, I would consider implementing it for MIA. However, I would implement a burn for a percentage of the treasury exit for any other CC, including NYC, because this would open the exit benefit to anyone wanting to hold NYC in this case.

Being free to exit means more capital freedom.

**Comment by CrypDohDS** [comment]
Great reading around here. So much to think about from really great community: Patrick, Donnie, Rapha, Tim, Miguel, and Freidger. Thank you.

I don't like the tax deduction burn idea. It seems messy and complex for many token holders. There are legal tax documents and government dependency requirements on getting this as a recognized transaction. Consider the owners of the billion plus tokens still at OKCoin. 

I would support merging the treasuries, rebranding, and ending the Miami agreement. Then we can do our yield funding proposals. 

I'm not for liquidations or token burns for treasury STX. Just seems to me that is what we have to build, do good, and call of our future. 

I'm all for wrapping up something with first the extension of the direct execute, pre-Nakamoto protocol requirements, and Clarity help from Whoabuddy again. 

Many good ideas have been discussed from everyone here. I really like the revolutionary concept of this project and it is worth saving. Let's not get nasty or personal in these dialogues. I have proposed before that developer work needs to be funded to treat those who work fairly. We need some serious cleanup to website, X, public documents, and honesty here if CityCoins rebuilds...in the meantime stack away holders! Derek.

**Comment by mavecillas** [comment]
I agree with @CrypDohDS and if we have to vote we should find a way to make it fair, so that those with the most tokens have a larger impact in a decision. Setting ground rules, like someone can’t claim receiving all the interest just cause they have a majority of the tokens. But I’m sure if we vote where the majority of tokens holders get a say the proposals will pass. Because those that have the most tokens surely want what’s best for them.

**Comment by Rapha-btc** [comment]
After our chat, Tim, I see why exiting based on tax benefits aligns well with CityCoins' aim to enhance urban life sustainably. By structuring donations so they're not burdensome for holders and treasuries, and possibly offset by mining revenues, we foster a virtuous cycle that boosts CityCoins. Hence, allowing tax deductions for those burning their coins, akin to making a donation, seems fitting. It benefits remaining holders with increased yields. Moreover, withdrawing from the treasury, an option for NYC, lacks appeal. It risks disrupting the ecosystem by draining the treasury.


Appreciating CrypDohDS and Miguel for their respectful dialogue, I lean against merging MIA and NYC. Building on Tim's insights, it's crucial that NYC and MIA preserve their unique characteristics, avoiding having NYC inherit potential risks like the MIA government favoring short-term PR and depleting the treasury, rather than collaborating on a sustainable mechanism feeding a flywheel effect.

MIA's risks are offset by potential rewards; the city collaborating could be very bullish for MIA. Risks and rewards often come together. 

Agreeing with Tim, we should maintain separate experiments. Following the "divide to conquer" adage, a successful citycoin model could inspire other cities. Conversely, merging citycoins risks total failure if the unified project fails.

I don't foresee scalability issues with keeping cities separate, given the scalability and replicability of code, particularly with human-readable Clarity smart contracts. I'd appreciate CryptoDohDs elaborating on his scalability concerns, as I currently see none.

You can now stack, claim stacking rewards, mine, and claim mining rewards on https://www.jing.cash/—an open-source UI. I'm finalizing this version with safety-focused post conditions. I hear that a more refined UI by a more experience dev. is also on the horizon!

**Comment by CrypDohDS** [comment]
Great comments Rapha. Unifying code and treasury is only cited if we had a Miami city agreement to leave principle in place. It appears Jason (Whoabuddy) seems to be our only volunteer developer and code editor at this time. I am a proponent of getting him compensated fairly.

**Comment by whoabuddy** [comment]
Closing this out following the shutdown of mining and stacking in CCIP-020.
